# Generated by Django 5.2.6 on 2025-09-19 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_boleto_data_pagamento_alter_boleto_data_emissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='data_emissao',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 1, 40, 38, 775546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 1, 40, 38, 775618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 1, 40, 38, 775292, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 1, 40, 38, 774322, tzinfo=datetime.timezone.utc)),
        ),
    ]
